export const COLOURS_LIST = [
  {label: 'The colour "Pink"', value: 'Pink'},
  {label: 'The colour "LightPink"', value: 'LightPink'},
  {label: 'The colour "HotPink"', value: 'HotPink'},
  {label: 'The colour "DeepPink"', value: 'DeepPink'},
  {label: 'The colour "PaleVioletRed"', value: 'PaleVioletRed'},
  {label: 'The colour "MediumVioletRed"', value: 'MediumVioletRed'},
  {label: 'The colour "Lavender"', value: 'Lavender'},
  {label: 'The colour "Thistle"', value: 'Thistle'},
  {label: 'The colour "Plum"', value: 'Plum'},
  {label: 'The colour "Orchid"', value: 'Orchid'},
  {label: 'The colour "Violet"', value: 'Violet'},
  {label: 'The colour "Fuchsia"', value: 'Fuchsia'},
  {label: 'The colour "Magenta"', value: 'Magenta'},
  {label: 'The colour "MediumOrchid"', value: 'MediumOrchid'},
  {label: 'The colour "DarkOrchid"', value: 'DarkOrchid'},
  {label: 'The colour "DarkViolet"', value: 'DarkViolet'},
  {label: 'The colour "BlueViolet"', value: 'BlueViolet'},
  {label: 'The colour "DarkMagenta"', value: 'DarkMagenta'},
  {label: 'The colour "Purple"', value: 'Purple'},
  {label: 'The colour "MediumPurple"', value: 'MediumPurple'},
  {label: 'The colour "MediumSlateBlue"', value: 'MediumSlateBlue'},
  {label: 'The colour "SlateBlue"', value: 'SlateBlue'},
  {label: 'The colour "DarkSlateBlue"', value: 'DarkSlateBlue'},
  {label: 'The colour "RebeccaPurple"', value: 'RebeccaPurple'},
  {label: 'The colour "Indigo"', value: 'Indigo'},
  {label: 'The colour "LightSalmon"', value: 'LightSalmon'},
  {label: 'The colour "Salmon"', value: 'Salmon'},
  {label: 'The colour "DarkSalmon"', value: 'DarkSalmon'},
  {label: 'The colour "LightCoral"', value: 'LightCoral'},
  {label: 'The colour "IndianRed"', value: 'IndianRed'},
  {label: 'The colour "Crimson"', value: 'Crimson'},
  {label: 'The colour "Red"', value: 'Red'},
  {label: 'The colour "FireBrick"', value: 'FireBrick'},
  {label: 'The colour "DarkRed"', value: 'DarkRed'},
  {label: 'The colour "Orange"', value: 'Orange'},
  {label: 'The colour "DarkOrange"', value: 'DarkOrange'},
  {label: 'The colour "Coral"', value: 'Coral'},
  {label: 'The colour "Tomato"', value: 'Tomato'},
  {label: 'The colour "OrangeRed"', value: 'OrangeRed'},
  {label: 'The colour "Gold"', value: 'Gold'},
  {label: 'The colour "Yellow"', value: 'Yellow'},
  {label: 'The colour "LightYellow"', value: 'LightYellow'},
  {label: 'The colour "LemonChiffon"', value: 'LemonChiffon'},
  {label: 'The colour "LightGoldenRodYellow"', value: 'LightGoldenRodYellow'},
  {label: 'The colour "PapayaWhip"', value: 'PapayaWhip'},
  {label: 'The colour "Moccasin"', value: 'Moccasin'},
  {label: 'The colour "PeachPuff"', value: 'PeachPuff'},
  {label: 'The colour "PaleGoldenRod"', value: 'PaleGoldenRod'},
  {label: 'The colour "Khaki"', value: 'Khaki'},
  {label: 'The colour "DarkKhaki"', value: 'DarkKhaki'},
  {label: 'The colour "GreenYellow"', value: 'GreenYellow'},
  {label: 'The colour "Chartreuse"', value: 'Chartreuse'},
  {label: 'The colour "LawnGreen"', value: 'LawnGreen'},
  {label: 'The colour "Lime"', value: 'Lime'},
  {label: 'The colour "LimeGreen"', value: 'LimeGreen'},
  {label: 'The colour "PaleGreen"', value: 'PaleGreen'},
  {label: 'The colour "LightGreen"', value: 'LightGreen'},
  {label: 'The colour "MediumSpringGreen"', value: 'MediumSpringGreen'},
  {label: 'The colour "SpringGreen"', value: 'SpringGreen'},
  {label: 'The colour "MediumSeaGreen"', value: 'MediumSeaGreen'},
  {label: 'The colour "SeaGreen"', value: 'SeaGreen'},
  {label: 'The colour "ForestGreen"', value: 'ForestGreen'},
  {label: 'The colour "Green"', value: 'Green'},
  {label: 'The colour "DarkGreen"', value: 'DarkGreen'},
  {label: 'The colour "YellowGreen"', value: 'YellowGreen'},
  {label: 'The colour "OliveDrab"', value: 'OliveDrab'},
  {label: 'The colour "DarkOliveGreen"', value: 'DarkOliveGreen'},
  {label: 'The colour "MediumAquaMarine"', value: 'MediumAquaMarine'},
  {label: 'The colour "DarkSeaGreen"', value: 'DarkSeaGreen'},
  {label: 'The colour "LightSeaGreen"', value: 'LightSeaGreen'},
  {label: 'The colour "DarkCyan"', value: 'DarkCyan'},
  {label: 'The colour "Teal"', value: 'Teal'},
  {label: 'The colour "Aqua"', value: 'Aqua'},
  {label: 'The colour "Cyan"', value: 'Cyan'},
  {label: 'The colour "LightCyan"', value: 'LightCyan'},
  {label: 'The colour "PaleTurquoise"', value: 'PaleTurquoise'},
  {label: 'The colour "Aquamarine"', value: 'Aquamarine'},
  {label: 'The colour "Turquoise"', value: 'Turquoise'},
  {label: 'The colour "MediumTurquoise"', value: 'MediumTurquoise'},
  {label: 'The colour "DarkTurquoise"', value: 'DarkTurquoise'},
  {label: 'The colour "CadetBlue"', value: 'CadetBlue'},
  {label: 'The colour "SteelBlue"', value: 'SteelBlue'},
  {label: 'The colour "LightSteelBlue"', value: 'LightSteelBlue'},
  {label: 'The colour "LightBlue"', value: 'LightBlue'},
  {label: 'The colour "PowderBlue"', value: 'PowderBlue'},
  {label: 'The colour "LightSkyBlue"', value: 'LightSkyBlue'},
  {label: 'The colour "SkyBlue"', value: 'SkyBlue'},
  {label: 'The colour "CornflowerBlue"', value: 'CornflowerBlue'},
  {label: 'The colour "DeepSkyBlue"', value: 'DeepSkyBlue'},
  {label: 'The colour "DodgerBlue"', value: 'DodgerBlue'},
  {label: 'The colour "RoyalBlue"', value: 'RoyalBlue'},
  {label: 'The colour "Blue"', value: 'Blue'},
  {label: 'The colour "MediumBlue"', value: 'MediumBlue'},
  {label: 'The colour "DarkBlue"', value: 'DarkBlue'},
  {label: 'The colour "Navy"', value: 'Navy'},
  {label: 'The colour "MidnightBlue"', value: 'MidnightBlue'},
  {label: 'The colour "Cornsilk"', value: 'Cornsilk'},
  {label: 'The colour "BlanchedAlmond"', value: 'BlanchedAlmond'},
  {label: 'The colour "Bisque"', value: 'Bisque'},
  {label: 'The colour "NavajoWhite"', value: 'NavajoWhite'},
  {label: 'The colour "Wheat"', value: 'Wheat'},
  {label: 'The colour "BurlyWood"', value: 'BurlyWood'},
  {label: 'The colour "Tan"', value: 'Tan'},
  {label: 'The colour "RosyBrown"', value: 'RosyBrown'},
  {label: 'The colour "SandyBrown"', value: 'SandyBrown'},
  {label: 'The colour "GoldenRod"', value: 'GoldenRod'},
  {label: 'The colour "DarkGoldenRod"', value: 'DarkGoldenRod'},
  {label: 'The colour "Peru"', value: 'Peru'},
  {label: 'The colour "Chocolate"', value: 'Chocolate'},
  {label: 'The colour "Olive"', value: 'Olive'},
  {label: 'The colour "SaddleBrown"', value: 'SaddleBrown'},
  {label: 'The colour "Sienna"', value: 'Sienna'},
  {label: 'The colour "Brown"', value: 'Brown'},
  {label: 'The colour "Maroon"', value: 'Maroon'},
  {label: 'The colour "White"', value: 'White'},
  {label: 'The colour "Snow"', value: 'Snow'},
  {label: 'The colour "HoneyDew"', value: 'HoneyDew'},
  {label: 'The colour "MintCream"', value: 'MintCream'},
  {label: 'The colour "Azure"', value: 'Azure'},
  {label: 'The colour "AliceBlue"', value: 'AliceBlue'},
  {label: 'The colour "GhostWhite"', value: 'GhostWhite'},
  {label: 'The colour "WhiteSmoke"', value: 'WhiteSmoke'},
  {label: 'The colour "SeaShell"', value: 'SeaShell'},
  {label: 'The colour "Beige"', value: 'Beige'},
  {label: 'The colour "OldLace"', value: 'OldLace'},
  {label: 'The colour "FloralWhite"', value: 'FloralWhite'},
  {label: 'The colour "Ivory"', value: 'Ivory'},
  {label: 'The colour "AntiqueWhite"', value: 'AntiqueWhite'},
  {label: 'The colour "Linen"', value: 'Linen'},
  {label: 'The colour "LavenderBlush"', value: 'LavenderBlush'},
  {label: 'The colour "MistyRose"', value: 'MistyRose'},
  {label: 'The colour "Gainsboro"', value: 'Gainsboro'},
  {label: 'The colour "LightGray"', value: 'LightGray'},
  {label: 'The colour "Silver"', value: 'Silver'},
  {label: 'The colour "DarkGray"', value: 'DarkGray'},
  {label: 'The colour "DimGray"', value: 'DimGray'},
  {label: 'The colour "Gray"', value: 'Gray'},
  {label: 'The colour "LightSlateGray"', value: 'LightSlateGray'},
  {label: 'The colour "SlateGray"', value: 'SlateGray'},
  {label: 'The colour "DarkSlateGray"', value: 'DarkSlateGray'},
  {label: 'The colour "Black"', value: 'Black'},

];

export const LANGUAGES_LIST=[
  { label: 'Afrikaans', value: 'af'},
  { label: 'Albanian', value: 'sq'},
  { label: 'Amharic', value: 'am'},
  { label: 'Arabic', value: 'ar'},
  { label: 'Armenian', value: 'hy'},
  { label: 'Azerbaijani', value: 'az'},
  { label: 'Basque', value: 'eu'},
  { label: 'Belarusian', value: 'be'},
  { label: 'Bengali', value: 'bn'},
  { label: 'Bosnian', value: 'bs'},
  { label: 'Bulgarian', value: 'bg'},
  { label: 'Catalan', value: 'ca'},
  { label: 'Cebuano', value: 'ceb'},
  { label: 'Chinese (Simplified)', value: 'zh-CN'},
  { label: 'Chinese (Traditional)', value: 'zh-TW'},
  { label: 'Corsican', value: 'co'},
  { label: 'Croatian', value: 'hr'},
  { label: 'Czech', value: 'cs'},
  { label: 'Danish', value: 'da'},
  { label: 'Dutch', value: 'nl'},
  { label: 'English', value: 'en'},
  { label: 'Esperanto', value: 'eo'},
  { label: 'Estonian', value: 'et'},
  { label: 'Finnish', value: 'fi'},
  { label: 'French', value: 'fr'},
  { label: 'Frisian', value: 'fy'},
  { label: 'Galician', value: 'gl'},
  { label: 'Georgian', value: 'ka'},
  { label: 'German', value: 'de'},
  { label: 'Greek', value: 'el'},
  { label: 'Gujarati', value: 'gu'},
  { label: 'Haitian Creole', value: 'ht'},
  { label: 'Hausa', value: 'ha'},
  { label: 'Hawaiian', value: 'haw'},
  { label: 'Hebrew', value: 'he'},
  { label: 'Hindi', value: 'hi'},
  { label: 'Hmong', value: 'hmn'},
  { label: 'Hungarian', value: 'hu'},
  { label: 'Icelandic', value: 'is'},
  { label: 'Igbo', value: 'ig'},
  { label: 'Indonesian', value: 'id'},
  { label: 'Irish', value: 'ga'},
  { label: 'Italian', value: 'it'},
  { label: 'Japanese', value: 'ja'},
  { label: 'Javanese', value: 'jv'},
  { label: 'Kannada', value: 'kn'},
  { label: 'Kazakh', value: 'kk'},
  { label: 'Khmer', value: 'km'},
  { label: 'Kinyarwanda', value: 'rw'},
  { label: 'Korean', value: 'ko'},
  { label: 'Kurdish', value: 'ku'},
  { label: 'Kyrgyz', value: 'ky'},
  { label: 'Lao', value: 'lo'},
  { label: 'Latvian', value: 'lv'},
  { label: 'Lithuanian', value: 'lt'},
  { label: 'Luxembourgish', value: 'lb'},
  { label: 'Macedonian', value: 'mk'},
  { label: 'Malagasy', value: 'mg'},
  { label: 'Malay', value: 'ms'},
  { label: 'Malayalam', value: 'ml'},
  { label: 'Maltese', value: 'mt'},
  { label: 'Maori', value: 'mi'},
  { label: 'Marathi', value: 'mr'},
  { label: 'Mongolian', value: 'mn'},
  { label: 'Myanmar (Burmese)', value: 'my'},
  { label: 'Nepali', value: 'ne'},
  { label: 'Norwegian', value: 'no'},
  { label: 'Nyanja (Chichewa)', value: 'ny'},
  { label: 'Odia (Oriya)', value: 'or'},
  { label: 'Pashto', value: 'ps'},
  { label: 'Persian', value: 'fa'},
  { label: 'Polish', value: 'pl'},
  { label: 'Portuguese (Portugal, Brazil)', value: 'pt'},
  { label: 'Punjabi', value: 'pa'},
  { label: 'Romanian', value: 'ro'},
  { label: 'Russian', value: 'ru'},
  { label: 'Samoan', value: 'sm'},
  { label: 'Scots Gaelic', value: 'gd'},
  { label: 'Serbian', value: 'sr'},
  { label: 'Sesotho', value: 'st'},
  { label: 'Shona', value: 'sn'},
  { label: 'Sindhi', value: 'sd'},
  { label: 'Sinhala (Sinhalese)', value: 'si'},
  { label: 'Slovak', value: 'sk'},
  { label: 'Slovenian', value: 'sl'},
  { label: 'Somali', value: 'so'},
  { label: 'Spanish', value: 'es'},
  { label: 'Sundanese', value: 'su'},
  { label: 'Swahili', value: 'sw'},
  { label: 'Swedish', value: 'sv'},
  { label: 'Tagalog (Filipino)', value: 'tl'},
  { label: 'Tajik', value: 'tg'},
  { label: 'Tamil', value: 'ta'},
  { label: 'Tatar', value: 'tt'},
  { label: 'Telugu', value: 'te'},
  { label: 'Thai', value: 'th'},
  { label: 'Turkish', value: 'tr'},
  { label: 'Turkmen', value: 'tk'},
  { label: 'Ukrainian', value: 'uk'},
  { label: 'Urdu', value: 'ur'},
  { label: 'Uyghur', value: 'ug'},
  { label: 'Uzbek', value: 'uz'},
  { label: 'Vietnamese', value: 'vi'},
  { label: 'Welsh', value: 'cy'},
  { label: 'Xhosa', value: 'xh'},
  { label: 'Yiddish', value: 'yi'},
  { label: 'Yoruba', value: 'yo'},
  { label: 'Zulu', value: 'zu'},
]